- hosts: all
  become: yes
  vars : 
    reboot : notnow
  tasks:  
 - name: Making changes to the yum.conf file
  shell : echo "Task will be updated befoer the reboot msg"
  args:
  executable: /bin/bash

- name : Update the server by using apt get  update
  apt:
  update_cache: yes


- name: install apache2
  apt: name=apache2 update_cache=yes state=latest

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
   - restart apache2


- name: Rebooting servers now ...
  command: shutdown -r now "Reboot required checking mesg"
  async: 0
  poll: 0
  sudo: true
  ignore_errors: true
  when: reboot == "now"
  register: rebooting

- name: Taking a nap while servers reboot...
  pause: seconds=200
  when: rebooting is changed

- name: Confirming servers are back online
  wait_for:
   host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
   delay: 30
   state: started
   search_regex: OpenSSH
   port: 22
   become: false
   when: reboot is changed
   delegate_to: localhost
